package Vista;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class VistaConsultar extends javax.swing.JFrame {

    
    public VistaConsultar() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUbicacionConsulta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionResult = new javax.swing.JTextArea();
        txtUbicacionResult = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        txtPrecioResult = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNombreConsulta = new javax.swing.JTextField();
        txtNombreResult = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUbicacionConsulta.setBackground(new java.awt.Color(255, 255, 204));
        txtUbicacionConsulta.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        txtUbicacionConsulta.setForeground(new java.awt.Color(51, 51, 51));
        txtUbicacionConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtUbicacionConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 78, 249, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ubicación de las Atracciones:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 223, 113, 23));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ubiacación");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 365, -1, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Precio Entrada");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 410, 128, -1));

        txtDescripcionResult.setColumns(20);
        txtDescripcionResult.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        txtUbicacionResult.setToolTipText("");
        getContentPane().add(txtUbicacionResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 370, 233, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 204));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 51, 51));
        btnVolver.setText("<--");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));
        getContentPane().add(txtPrecioResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 410, 233, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre de la Atraccion a consultar:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 310, 29));

        txtNombreConsulta.setBackground(new java.awt.Color(255, 255, 204));
        txtNombreConsulta.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        txtNombreConsulta.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 37, 249, -1));

        txtNombreResult.setToolTipText("");
        getContentPane().add(txtNombreResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 183, 233, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Nombre");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 183, -1, 26));

        btnConsultar.setBackground(new java.awt.Color(255, 255, 204));
        btnConsultar.setText("Consultar");
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 116, 119, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/FondoConsulta.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUbicacionConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionConsultaActionPerformed

    private void txtNombreConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConsultaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtDescripcionResult;
    public javax.swing.JTextField txtNombreConsulta;
    public javax.swing.JTextField txtNombreResult;
    public javax.swing.JTextField txtPrecioResult;
    public javax.swing.JTextField txtUbicacionConsulta;
    public javax.swing.JTextField txtUbicacionResult;
    // End of variables declaration//GEN-END:variables


   public void variedadPasstas(int a , int b){
       JOptionPane.showMessageDialog(null, "Existen "+a+" registros de pastas variedad fresca y "+b +" registros de pastas variedad seca");
   }
   public void ListaFormas (List<String> listaFormas){
       JOptionPane.showMessageDialog(null, "Las formas de pastas almacenadas son : "+listaFormas);
   }
   public void CantidadEnCiudad(int a){
      JOptionPane.showMessageDialog(null, "De esta ciudad son originarias "+a+" pastas de las que se encuentran registradas");
}
   public void error(String txt){
       JOptionPane.showMessageDialog(null, txt, "Error",JOptionPane.ERROR_MESSAGE);
   }
   public void noExiste(){
       JOptionPane.showMessageDialog(null, "No existe registro de esta pasta", "Error", JOptionPane.ERROR_MESSAGE);
   }
   public void tablaUbicaciones(String [][] data){
         // Crear un modelo de tabla
                    String[] columnNames = {"Nombre"};
                    // Crear un modelo de tabla no editable
                    DefaultTableModel model = new DefaultTableModel(data, columnNames) {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                            return false;
                        }
                    };
                    // Crear una tabla con el modelo
                    JTable table = new JTable(model);

                    // Agregar la tabla a un JScrollPane (en caso de que los datos no entren en la ventana)
                    JScrollPane scrollPane = new JScrollPane(table);

                    // Mostrar la tabla en un diálogo JOptionPane
                    JOptionPane.showMessageDialog(null, scrollPane, "Ubicaciones", JOptionPane.PLAIN_MESSAGE);
    }
   

          
}
