package Vista;

import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.JOptionPane;
public class VistaUsuario extends javax.swing.JFrame {

    public VistaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        comboxUsuarios = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMapa = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnCalificar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboxUsuarios.setBackground(new java.awt.Color(255, 255, 204));
        comboxUsuarios.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        comboxUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        comboxUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxUsuariosItemStateChanged(evt);
            }
        });
        comboxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(comboxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 204));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 51, 51));
        btnVolver.setText("<--");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        btnSalir.setBackground(new java.awt.Color(255, 255, 204));
        btnSalir.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, -1));

        btnMapa.setBackground(new java.awt.Color(255, 255, 204));
        btnMapa.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnMapa.setForeground(new java.awt.Color(51, 51, 51));
        btnMapa.setText("Mapa");
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 100, -1));

        btnConsultar.setBackground(new java.awt.Color(255, 255, 204));
        btnConsultar.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(51, 51, 51));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, -1));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 204));
        btnSeleccionar.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(51, 51, 51));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        btnCalificar.setBackground(new java.awt.Color(255, 255, 204));
        btnCalificar.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnCalificar.setForeground(new java.awt.Color(51, 51, 51));
        btnCalificar.setText("Calificar");
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 100, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));
        txtNombre.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 210, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Calificación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        txtCalificacion.setBackground(new java.awt.Color(255, 255, 204));
        txtCalificacion.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        txtCalificacion.setForeground(new java.awt.Color(51, 51, 51));
        txtCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 210, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 204));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 400, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondoUsuario.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       
    }//GEN-LAST:event_btnVolverActionPerformed

    private void comboxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxUsuariosActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalificacionActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void comboxUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxUsuariosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxUsuariosItemStateChanged

    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMapaActionPerformed

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalificar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnMapa;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSeleccionar;
    public javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    public javax.swing.JComboBox<String> comboxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField txtCalificacion;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

   public void limpiar() {//Acción boton limpiar
        txtNombre.setText("");     
        txtCalificacion.setText("");
        
        buttonGroup1.clearSelection();
    }
      public void error(String txt){
       JOptionPane.showMessageDialog(null, txt, "Error",JOptionPane.ERROR_MESSAGE);
   }
      
       public void msg(String txt){
       JOptionPane.showMessageDialog(null, txt, "Eliminada",JOptionPane.INFORMATION_MESSAGE);
   }  
}